export const SET_CATEGORY_NAME = 'SET_CATEGORY_NAME';
export const SET_FULL_PAGE_LOADER = 'SET_FULL_PAGE_LOADER';
export const SET_CATEGORY_DATA = 'SET_CATEGORY_DATA';
export const SET_LOGIN_PAGE_MODAL = 'SET_LOGIN_PAGE_MODAL';
export const SET_REGISTER_PAGE_MODAL = 'SET_REGISTER_PAGE_MODAL';
export const SET_LANDING_PAGE = 'SET_LANDING_PAGE';
